// Datos simulados para la productividad de empleados
export const mockEmployeeProductivityData = [
  {
    id: "emp-1",
    name: "Juan Pérez",
    position: "Cajero",
    location: "BR Cabildo",
    score: 92,
    salesPerHour: 1850,
    salesTrend: "up",
    attendance: 98,
    lateCount: 0,
    cashAccuracy: 99.8,
    stockAccuracy: 99.5,
    alerts: 0,
    date: "2023-11-01",
  },
  {
    id: "emp-2",
    name: "María López",
    position: "Cajera",
    location: "BR Carranza",
    score: 65,
    salesPerHour: 1200,
    salesTrend: "down",
    attendance: 85,
    lateCount: 3,
    cashAccuracy: 97.5,
    stockAccuracy: 98.0,
    alerts: 2,
    date: "2023-11-01",
  },
  {
    id: "emp-3",
    name: "Carlos Rodríguez",
    position: "Cocinero",
    location: "BR Pacífico",
    score: 88,
    salesPerHour: 1650,
    salesTrend: "up",
    attendance: 95,
    lateCount: 1,
    cashAccuracy: 99.2,
    stockAccuracy: 99.0,
    alerts: 0,
    date: "2023-11-01",
  },
  {
    id: "emp-4",
    name: "Ana Martínez",
    position: "Encargada",
    location: "BR Cabildo",
    score: 90,
    salesPerHour: 1750,
    salesTrend: "up",
    attendance: 97,
    lateCount: 0,
    cashAccuracy: 99.5,
    stockAccuracy: 99.2,
    alerts: 0,
    date: "2023-11-01",
  },
  {
    id: "emp-5",
    name: "Roberto Fernández",
    position: "Cajero",
    location: "BR Local 4",
    score: 78,
    salesPerHour: 1450,
    salesTrend: "neutral",
    attendance: 90,
    lateCount: 2,
    cashAccuracy: 98.5,
    stockAccuracy: 98.8,
    alerts: 1,
    date: "2023-11-01",
  },
  {
    id: "emp-6",
    name: "Laura Gómez",
    position: "Cocinera",
    location: "BR Local 5",
    score: 85,
    salesPerHour: 1600,
    salesTrend: "up",
    attendance: 93,
    lateCount: 1,
    cashAccuracy: 99.0,
    stockAccuracy: 98.5,
    alerts: 0,
    date: "2023-11-01",
  },
  {
    id: "emp-7",
    name: "Diego Sánchez",
    position: "Cajero",
    location: "BR Carranza",
    score: 72,
    salesPerHour: 1350,
    salesTrend: "down",
    attendance: 88,
    lateCount: 2,
    cashAccuracy: 98.0,
    stockAccuracy: 97.5,
    alerts: 1,
    date: "2023-11-01",
  },
  {
    id: "emp-8",
    name: "Sofía Torres",
    position: "Encargada",
    location: "BR Pacífico",
    score: 89,
    salesPerHour: 1700,
    salesTrend: "up",
    attendance: 96,
    lateCount: 0,
    cashAccuracy: 99.3,
    stockAccuracy: 99.1,
    alerts: 0,
    date: "2023-11-01",
  },
  {
    id: "emp-9",
    name: "Javier Acosta",
    position: "Cocinero",
    location: "BR Local 4",
    score: 82,
    salesPerHour: 1550,
    salesTrend: "up",
    attendance: 92,
    lateCount: 1,
    cashAccuracy: 98.8,
    stockAccuracy: 98.6,
    alerts: 0,
    date: "2023-11-01",
  },
  {
    id: "emp-10",
    name: "Valentina Díaz",
    position: "Cajera",
    location: "BR Local 5",
    score: 75,
    salesPerHour: 1400,
    salesTrend: "neutral",
    attendance: 89,
    lateCount: 2,
    cashAccuracy: 98.2,
    stockAccuracy: 98.0,
    alerts: 1,
    date: "2023-11-01",
  },
  {
    id: "emp-11",
    name: "Martín Herrera",
    position: "Cajero",
    location: "BR Cabildo",
    score: 80,
    salesPerHour: 1500,
    salesTrend: "neutral",
    attendance: 91,
    lateCount: 1,
    cashAccuracy: 98.7,
    stockAccuracy: 98.5,
    alerts: 0,
    date: "2023-11-01",
  },
  {
    id: "emp-12",
    name: "Lucía Mendoza",
    position: "Cocinera",
    location: "BR Carranza",
    score: 86,
    salesPerHour: 1620,
    salesTrend: "up",
    attendance: 94,
    lateCount: 0,
    cashAccuracy: 99.1,
    stockAccuracy: 98.9,
    alerts: 0,
    date: "2023-11-01",
  },
  {
    id: "emp-13",
    name: "Mateo Vargas",
    position: "Cajero",
    location: "BR Pacífico",
    score: 70,
    salesPerHour: 1300,
    salesTrend: "down",
    attendance: 86,
    lateCount: 3,
    cashAccuracy: 97.8,
    stockAccuracy: 97.2,
    alerts: 2,
    date: "2023-11-01",
  },
  {
    id: "emp-14",
    name: "Camila Rojas",
    position: "Encargada",
    location: "BR Local 4",
    score: 87,
    salesPerHour: 1650,
    salesTrend: "up",
    attendance: 95,
    lateCount: 0,
    cashAccuracy: 99.2,
    stockAccuracy: 99.0,
    alerts: 0,
    date: "2023-11-01",
  },
  {
    id: "emp-15",
    name: "Nicolás Peralta",
    position: "Cocinero",
    location: "BR Local 5",
    score: 83,
    salesPerHour: 1580,
    salesTrend: "up",
    attendance: 93,
    lateCount: 1,
    cashAccuracy: 98.9,
    stockAccuracy: 98.7,
    alerts: 0,
    date: "2023-11-01",
  },
  // Datos para fechas anteriores para mostrar tendencias
  {
    id: "emp-1",
    name: "Juan Pérez",
    position: "Cajero",
    location: "BR Cabildo",
    score: 90,
    salesPerHour: 1800,
    salesTrend: "up",
    attendance: 97,
    lateCount: 0,
    cashAccuracy: 99.6,
    stockAccuracy: 99.3,
    alerts: 0,
    date: "2023-10-01",
  },
  {
    id: "emp-1",
    name: "Juan Pérez",
    position: "Cajero",
    location: "BR Cabildo",
    score: 88,
    salesPerHour: 1750,
    salesTrend: "up",
    attendance: 96,
    lateCount: 1,
    cashAccuracy: 99.4,
    stockAccuracy: 99.1,
    alerts: 0,
    date: "2023-09-01",
  },
  {
    id: "emp-1",
    name: "Juan Pérez",
    position: "Cajero",
    location: "BR Cabildo",
    score: 86,
    salesPerHour: 1700,
    salesTrend: "neutral",
    attendance: 95,
    lateCount: 1,
    cashAccuracy: 99.2,
    stockAccuracy: 98.9,
    alerts: 0,
    date: "2023-08-01",
  },
  {
    id: "emp-1",
    name: "Juan Pérez",
    position: "Cajero",
    location: "BR Cabildo",
    score: 84,
    salesPerHour: 1650,
    salesTrend: "neutral",
    attendance: 94,
    lateCount: 1,
    cashAccuracy: 99.0,
    stockAccuracy: 98.7,
    alerts: 0,
    date: "2023-07-01",
  },
  {
    id: "emp-1",
    name: "Juan Pérez",
    position: "Cajero",
    location: "BR Cabildo",
    score: 82,
    salesPerHour: 1600,
    salesTrend: "neutral",
    attendance: 93,
    lateCount: 1,
    cashAccuracy: 98.8,
    stockAccuracy: 98.5,
    alerts: 0,
    date: "2023-06-01",
  },
  {
    id: "emp-1",
    name: "Juan Pérez",
    position: "Cajero",
    location: "BR Cabildo",
    score: 80,
    salesPerHour: 1600,
    salesTrend: "neutral",
    attendance: 93,
    lateCount: 1,
    cashAccuracy: 98.8,
    stockAccuracy: 98.5,
    alerts: 0,
    date: "2023-06-01",
  },
]

// Datos simulados para factores externos
export const mockExternalFactors = [
  {
    date: "2023-11-01",
    weather: "rainy",
    holiday: false,
    events: [],
    salesImpact: -0.25,
  },
  {
    date: "2023-11-02",
    weather: "clear",
    holiday: false,
    events: [],
    salesImpact: 0,
  },
  {
    date: "2023-11-03",
    weather: "clear",
    holiday: false,
    events: ["Partido de fútbol local"],
    salesImpact: 0.15,
  },
  {
    date: "2023-11-04",
    weather: "rainy",
    holiday: false,
    events: [],
    salesImpact: -0.25,
  },
  {
    date: "2023-11-05",
    weather: "clear",
    holiday: false,
    events: [],
    salesImpact: 0,
  },
  {
    date: "2023-11-06",
    weather: "clear",
    holiday: true,
    events: [],
    salesImpact: -0.2,
  },
  {
    date: "2023-11-07",
    weather: "rainy",
    holiday: false,
    events: [],
    salesImpact: -0.25,
  },
]

