// Datos ficticios para el sistema de control anti-robo

// Productos
export const mockProducts = [
  { id: "prod-1", name: "Empanadas", expectedInitialStock: 100, expectedFinalStock: 50 },
  { id: "prod-2", name: "Pizzas Muzzarella", expectedInitialStock: 20, expectedFinalStock: 10 },
  { id: "prod-3", name: "Pizzas Doble Muzzarella", expectedInitialStock: 15, expectedFinalStock: 5 },
  { id: "prod-4", name: "Medialunas de Grasa", expectedInitialStock: 80, expectedFinalStock: 30 },
  { id: "prod-5", name: "Medialunas de Manteca", expectedInitialStock: 80, expectedFinalStock: 20 },
  { id: "prod-6", name: "Almibar", expectedInitialStock: 30, expectedFinalStock: 15 },
  { id: "prod-7", name: "Pepsi 500ml", expectedInitialStock: 50, expectedFinalStock: 20 },
  { id: "prod-8", name: "7UP 500ml", expectedInitialStock: 40, expectedFinalStock: 15 },
  { id: "prod-9", name: "Fanta 500ml", expectedInitialStock: 30, expectedFinalStock: 10 },
  { id: "prod-10", name: "Agua sin Gas 500ml", expectedInitialStock: 40, expectedFinalStock: 20 },
  { id: "prod-11", name: "Agua con Gas 500ml", expectedInitialStock: 30, expectedFinalStock: 15 },
  { id: "prod-12", name: "Quilmes 500ml", expectedInitialStock: 40, expectedFinalStock: 20 },
  { id: "prod-13", name: "Pepsi Grande", expectedInitialStock: 20, expectedFinalStock: 10 },
  { id: "prod-14", name: "7UP Grande", expectedInitialStock: 15, expectedFinalStock: 5 },
  { id: "prod-15", name: "Fanta Grande", expectedInitialStock: 15, expectedFinalStock: 5 },
]

// Usuarios
export const mockUsers = [
  { id: "user-1", name: "Juan Pérez", email: "juan@example.com", role: "encargado" },
  { id: "user-2", name: "María López", email: "maria@example.com", role: "encargado" },
  { id: "user-3", name: "Carlos Gómez", email: "carlos@example.com", role: "encargado" },
  { id: "user-4", name: "Ana Martínez", email: "ana@example.com", role: "admin" },
  { id: "user-5", name: "Roberto Sánchez", email: "roberto@example.com", role: "admin" },
]

// Proveedores
export const mockProviders = [
  { id: "prov-1", name: "Fabian Bebidas" },
  { id: "prov-2", name: "Lucho Tango" },
  { id: "prov-3", name: "Brozziano" },
]

// Datos de ventas (simulando datos de Datalive)
export const mockSalesData = {
  id: "sales-1",
  localId: "local-1",
  localName: "BR Cabildo",
  date: new Date().toISOString(),
  shift: "mañana",
  items: [
    {
      productId: "prod-1",
      productName: "Empanadas",
      quantity: 45,
      unitPrice: 500,
      totalPrice: 22500,
      paymentMethod: "Efectivo",
    },
    {
      productId: "prod-1",
      productName: "Empanadas",
      quantity: 15,
      unitPrice: 550,
      totalPrice: 8250,
      paymentMethod: "PedidosYa",
    },
    {
      productId: "prod-2",
      productName: "Pizzas Muzzarella",
      quantity: 8,
      unitPrice: 3500,
      totalPrice: 28000,
      paymentMethod: "Efectivo",
    },
    {
      productId: "prod-2",
      productName: "Pizzas Muzzarella",
      quantity: 3,
      unitPrice: 3800,
      totalPrice: 11400,
      paymentMethod: "Rappi",
    },
    {
      productId: "prod-3",
      productName: "Pizzas Doble Muzzarella",
      quantity: 5,
      unitPrice: 4000,
      totalPrice: 20000,
      paymentMethod: "Tarjeta de Crédito",
    },
    {
      productId: "prod-3",
      productName: "Pizzas Doble Muzzarella",
      quantity: 2,
      unitPrice: 4300,
      totalPrice: 8600,
      paymentMethod: "PedidosYa",
    },
    {
      productId: "prod-4",
      productName: "Medialunas de Grasa",
      quantity: 40,
      unitPrice: 300,
      totalPrice: 12000,
      paymentMethod: "Efectivo",
    },
    {
      productId: "prod-5",
      productName: "Medialunas de Manteca",
      quantity: 35,
      unitPrice: 350,
      totalPrice: 12250,
      paymentMethod: "Efectivo",
    },
    {
      productId: "prod-6",
      productName: "Almibar",
      quantity: 12,
      unitPrice: 400,
      totalPrice: 4800,
      paymentMethod: "Efectivo",
    },
    {
      productId: "prod-7",
      productName: "Pepsi 500ml",
      quantity: 25,
      unitPrice: 800,
      totalPrice: 20000,
      paymentMethod: "Efectivo",
    },
    {
      productId: "prod-8",
      productName: "7UP 500ml",
      quantity: 18,
      unitPrice: 800,
      totalPrice: 14400,
      paymentMethod: "Efectivo",
    },
    {
      productId: "prod-9",
      productName: "Fanta 500ml",
      quantity: 15,
      unitPrice: 800,
      totalPrice: 12000,
      paymentMethod: "Efectivo",
    },
    {
      productId: "prod-10",
      productName: "Agua sin Gas 500ml",
      quantity: 20,
      unitPrice: 700,
      totalPrice: 14000,
      paymentMethod: "Efectivo",
    },
    {
      productId: "prod-11",
      productName: "Agua con Gas 500ml",
      quantity: 12,
      unitPrice: 700,
      totalPrice: 8400,
      paymentMethod: "Efectivo",
    },
    {
      productId: "prod-12",
      productName: "Quilmes 500ml",
      quantity: 18,
      unitPrice: 1200,
      totalPrice: 21600,
      paymentMethod: "Efectivo",
    },
    {
      productId: "prod-13",
      productName: "Pepsi Grande",
      quantity: 8,
      unitPrice: 1500,
      totalPrice: 12000,
      paymentMethod: "Efectivo",
    },
    {
      productId: "prod-14",
      productName: "7UP Grande",
      quantity: 6,
      unitPrice: 1500,
      totalPrice: 9000,
      paymentMethod: "Efectivo",
    },
    {
      productId: "prod-15",
      productName: "Fanta Grande",
      quantity: 5,
      unitPrice: 1500,
      totalPrice: 7500,
      paymentMethod: "Efectivo",
    },
  ],
  totalAmount: 246700,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  lastSync: new Date().toISOString(),
}

// Alertas
export const mockAlerts = [
  {
    id: "alert-1",
    localId: "local-1",
    localName: "BR Cabildo",
    date: new Date().toISOString(),
    shift: "mañana",
    userId: "user-1",
    type: "stock",
    severity: "alta",
    title: "Diferencia significativa en stock",
    description: "Faltante de 10 unidades de Empanadas (10% del stock)",
    differenceAmount: -10,
    differencePercentage: 10,
    status: "pendiente",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "alert-2",
    localId: "local-2",
    localName: "BR Carranza",
    date: new Date(Date.now() - 86400000).toISOString(), // Ayer
    shift: "tarde",
    userId: "user-2",
    type: "caja",
    severity: "media",
    title: "Diferencia en caja",
    description: "Faltante de $6,500 en caja (3% del total)",
    differenceAmount: -6500,
    differencePercentage: 3,
    status: "revisada",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 43200000).toISOString(),
  },
  {
    id: "alert-3",
    localId: "local-3",
    localName: "BR Pacifico",
    date: new Date(Date.now() - 172800000).toISOString(), // Hace 2 días
    shift: "noche",
    userId: "user-3",
    type: "decomiso",
    severity: "alta",
    title: "Decomiso excesivo",
    description: "Decomiso del 5% de las Pizzas Muzzarella (superior al límite del 1%)",
    differenceAmount: 5,
    differencePercentage: 5,
    status: "resuelta",
    resolution:
      "Se verificó con el encargado. El decomiso fue justificado por problemas con el horno que quemó varias pizzas.",
    resolvedBy: "user-5",
    resolvedAt: new Date(Date.now() - 129600000).toISOString(),
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date(Date.now() - 129600000).toISOString(),
  },
]



